import test from 'node:test';
import assert from 'node:assert';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { loadConfig } from '@nova/shared';
import { BUILT_IN_TOOLS, executeTool } from './tools.js';

const OWNER = { isOwner: true, sessionId: 'owner-session' };
const GUEST = { isOwner: false, sessionId: 'guest-session' };

const tempDir = fs.mkdtempSync(path.join(os.tmpdir(), 'nova-tools-test-'));
const cleanupPaths: string[] = [];

test.after(() => {
  fs.rmSync(tempDir, { recursive: true, force: true });
  for (const p of cleanupPaths) {
    if (fs.existsSync(p)) fs.unlinkSync(p);
  }
});

test('BUILT_IN_TOOLS exposes uniquely named tools with descriptions and parameters', () => {
  const names = BUILT_IN_TOOLS.map(t => t.name);

  assert.strictEqual(new Set(names).size, names.length, 'Tool names must be unique');
  for (const tool of BUILT_IN_TOOLS) {
    assert.ok(tool.description.length > 0, `${tool.name} must document what it does`);
    assert.strictEqual(typeof tool.parameters, 'object');
  }
});

test('Owner-only tools are refused for guest sessions', async () => {
  for (const toolName of ['file_write', 'browser', 'skill_write', 'business_analytics_report']) {
    const result = await executeTool(toolName, {}, GUEST);

    assert.strictEqual(result.success, false, `${toolName} must be blocked for guests`);
    assert.match(result.output, /Security Exception/);
    assert.ok(result.output.includes(toolName), 'The rejection must name the blocked tool');
  }
});

test('Unknown tool names are rejected', async () => {
  const result = await executeTool('definitely_not_a_tool', {}, OWNER);

  assert.strictEqual(result.success, false);
  assert.match(result.output, /Unknown tool: definitely_not_a_tool/);
});

test('file_write then file_read round-trips content and creates missing directories', async () => {
  const filePath = path.join(tempDir, 'nested', 'note.txt');

  const write = await executeTool('file_write', { filePath, content: 'hello nova' }, OWNER);
  assert.strictEqual(write.success, true);
  assert.match(write.output, /Successfully wrote to file/);
  assert.ok(fs.existsSync(filePath), 'Parent directories must be created on demand');

  const read = await executeTool('file_read', { filePath }, OWNER);
  assert.deepStrictEqual(read, { success: true, output: 'hello nova' });
});

test('file_read reports a missing file instead of throwing', async () => {
  const result = await executeTool('file_read', { filePath: path.join(tempDir, 'does-not-exist.txt') }, OWNER);

  assert.strictEqual(result.success, false);
  assert.match(result.output, /File not found/);
});

test('file_read is available to guest sessions', async () => {
  const filePath = path.join(tempDir, 'public.txt');
  fs.writeFileSync(filePath, 'readable by guests', 'utf-8');

  const result = await executeTool('file_read', { filePath }, GUEST);

  assert.strictEqual(result.success, true);
  assert.strictEqual(result.output, 'readable by guests');
});

test('Tool failures are converted into a structured error result', async () => {
  // A directory path makes the underlying write throw, which must be caught.
  const result = await executeTool('file_write', { filePath: tempDir, content: 'boom' }, OWNER);

  assert.strictEqual(result.success, false);
  assert.match(result.output, /Tool Execution Error/);
});

test('bash runs a host command for the owner and returns stdout', async () => {
  const result = await executeTool('bash', { command: 'echo nova-bash-check' }, OWNER);

  assert.strictEqual(result.success, true);
  assert.match(result.output, /nova-bash-check/);
});

test('skill_write sanitizes the skill filename before persisting it', async () => {
  const skillsDir = loadConfig().paths.skills;
  const expectedPath = path.join(skillsDir, 'zz-testskillreport.md');
  cleanupPaths.push(expectedPath);

  const result = await executeTool(
    'skill_write',
    { skillName: 'ZZ-Test Skill/Report!', markdownContent: '# Report\nGenerated by a unit test.' },
    OWNER
  );

  assert.strictEqual(result.success, true);
  assert.ok(result.output.includes(expectedPath), 'The tool must report where the skill was written');
  assert.strictEqual(fs.readFileSync(expectedPath, 'utf-8'), '# Report\nGenerated by a unit test.');
});

test('web_search parses DuckDuckGo results and degrades gracefully', async () => {
  const originalFetch = globalThis.fetch;

  try {
    (globalThis as any).fetch = async () => ({
      ok: true,
      status: 200,
      text: async () => `
        <a class="result__url" href="#"> example.com </a>
        <a class="result__snippet" href="#">An <b>example</b> snippet</a>
      `,
    });

    const parsed = await executeTool('web_search', { query: 'nova assistant' }, GUEST);
    assert.strictEqual(parsed.success, true);
    assert.match(parsed.output, /1\. example\.com/);
    assert.match(parsed.output, /Snippet: An example snippet/);

    (globalThis as any).fetch = async () => ({ ok: true, status: 200, text: async () => '<html></html>' });
    const empty = await executeTool('web_search', { query: 'nothing here' }, GUEST);
    assert.strictEqual(empty.success, true);
    assert.match(empty.output, /No search results found/);

    (globalThis as any).fetch = async () => ({ ok: false, status: 503, text: async () => '' });
    const failed = await executeTool('web_search', { query: 'nova assistant' }, GUEST);
    assert.strictEqual(failed.success, false);
    assert.match(failed.output, /Web Search Error: DDG status: 503/);
  } finally {
    (globalThis as any).fetch = originalFetch;
  }
});

test('code_exec runs owner JavaScript inline and reports interpreter failures', async () => {
  const ok = await executeTool('code_exec', { language: 'javascript', code: 'console.log(6 * 7)' }, OWNER);
  assert.strictEqual(ok.success, true);
  assert.match(ok.output, /42/);

  const failed = await executeTool('code_exec', { language: 'javascript', code: 'throw new Error("kaboom")' }, OWNER);
  assert.strictEqual(failed.success, false);
  assert.match(failed.output, /JavaScript Execution Failed/);

  const unsupported = await executeTool('code_exec', { language: 'brainfuck', code: '+++' }, OWNER);
  assert.strictEqual(unsupported.success, false);
  assert.match(unsupported.output, /Unsupported language: brainfuck/);
});

test('business_analytics_report summarizes the requested period for the owner', async () => {
  const result = await executeTool('business_analytics_report', { period: 'weekly' }, OWNER);

  assert.strictEqual(result.success, true);
  assert.match(result.output, /Business Analytics Report \(WEEKLY\)/);
  assert.match(result.output, /Revenue: \$\d+\.\d{2}/);
  assert.match(result.output, /Unique Visitors: \d+/);
});
